import mongoose from 'mongoose';

const FundingSchema = new mongoose.Schema({
    Name: String,
    Technology: String,
    'Prop Type': String,
    AngelList: String,
    Crunchbase: String,
    Domain: String,
    'HQ Address': String,
    City: String,
    State: String,
    Zip: String,
    '# Founders': Number,
    Founded: Number,
    'Years Active': Number,
    '# of Funding Rounds': Number,
    'Valuation Rank': Number,
    'Funding/Year Rank': Number,
    'Total Funding Rank': Number,
    'ARR Rank': String,
    'CAFR Rank': String,
    Avg: {
        ' Funding/Year': String
    },
    'ARR/Funds Raised': String,
    'Total Funding': String,
    'Estimated ARR': String,
    'CFRGR (Compound Funding Round Growth Rate)': String,
    CAFR: String,
    'Latest Valuation': String,
    'Latest Valuation Year': Number,
    Accelerator: String,
    'Accelerator 2': String,
    'Pre-Seed Date': String,
    'Pre-Seed $': String,
    'Seed Date': String,
    'Seed $': String,
    'Bridge Date': String,
    'Bridge $': String,
    'A Round Date': String,
    'A Round $': String,
    'B Round Date': String,
    'B Round $': String,
    'C Round Date': String,
    'C Round $': String,
    'D Round Date': String,
    'D Round $': String,
    'E Round Date': String,
    'E Round $': String,
    'F Round Date': String,
    'F Round $': String,
    'G Round Date': String,
    'G Round $': String,
    'H Round Date': String,
    'H Round $': String,
    'Unknown Series Date': String,
    'Unknown Series $': String,
    'Non-Dilutive Round Date': String,
    'Non-Dilutive Round $': String,
    'Exit Date': String,
    'Exit $': String,
    Acquirer: String
});

// Export the model
export default mongoose.model('Funding', FundingSchema, 'funding_DB');